### ISSUE TITLE
Add Google Analytic

### ISSUE THREAD

**Issue by thinkerou** [google/docsy#48] opened 2019-03-05 01:28 UTC

**Comment by theletterf** [comment] 2019-07-18 16:00
You can already do that. It’s in the docs. 

https://www.docsy.dev/docs/adding-content/feedback/

**Comment by theletterf** [comment] 2019-07-18 16:01
Oh I see. You didn’t close this one.

**Comment by chalin** [comment] 2022-11-01 22:32
I don't understand what the issue is here. Do you @LisaFC? Based on #49, I get the impression that the intent was to have Docsy support GA, which it clearly does now. I'm going to close this issue. Feel free to open a new one if something is still missing.

**Closed by chalin** 2022-11-01 22:32 UTC
