### ISSUE TITLE
New version of Algolia search breaks DOCSY search

### ISSUE THREAD

**Issue by prdsoftware** [google/docsy#845] opened 2022-01-18 20:54 UTC
There is a new version of Algolia search that has a different interface that doesn't seem to work with Docsy.

The new Algolia DocSearch no longer uses the ".td-search-input" as an input parameter in the new javascript.
https://www.docsy.dev/docs/adding-content/navigation/#configure-algolia-docsearch

The new v3 Algolia JS doco is here and uses "container" instead
https://docsearch.algolia.com/docs/docsearch-v3/

This seems like something Docsy has to update to?  Not sure what the implications are here, but posting here for someone who might know a bit more about this.

Thanks Docsy team!

**Comment by LisaFC** [comment] 2022-01-19 10:17
Yes, looks like we'd need to update if we wanted to use v3. @alexearnshaw added our Algolia integration but I don't know how free she is to look at it - does anyone else fancy taking a look?

Duplicate of #738

**Comment by LisaFC** [comment] 2022-01-19 10:18
Duplicate of #738

**Comment by Symbolics** [comment] 2022-03-07 00:29
Just wonder where this is in the priority queue. Algolia isn't updating the search index for the sites after their transition, and new content is no longer being captured.

**Comment by LisaFC** [comment] 2022-03-07 10:10
So is it the case that if you move to v3 it stops working, or are earlier versions of Algolia not working either?

**Comment by Symbolics** [comment] 2022-03-07 10:23
I haven't moved to v3 yet because the only site I maintain is using Docsy. It appears that if you don't move, then the old version has stopped working.

**Comment by prdsoftware** [comment] 2022-03-07 10:24
My understanding is that v2 indexes are no longer be updated, meaning that new content is not searchable, and DOCSY currently doesn't support moving to v3 because of the not supporting the new interface.    This means that Algolia is no longer a viable search option for DOCSY until the v3 interface is supported.

**Comment by LisaFC** [comment] 2022-03-07 11:16
Ah right, I thought v2 was still working so it was only urgent if users needed v3 features, if it's entirely broken then yes, we should get it fixed ASAP.

**Comment by prdsoftware** [comment] 2022-04-12 20:28
The new Algolia search box is different from v2, but it's fine the way it is IMO.  It's got more functionality, and uses the latest index, so I say go for it.  Thanks for your work on this.

Looking forward to seeing this change make it into Docsy.

**Closed** 2022-04-30 18:04 UTC
Labels: duplicate, search
