### ISSUE TITLE
TypeError: Invalid PostCSS Plugin found at: plugins[0]

### ISSUE THREAD

**Issue by brunoamaral** [google/docsy#337] opened 2020-09-16 15:07 UTC
I'm trying to build a site inside a docker container, but it's throwing out the error 

`TypeError: Invalid PostCSS Plugin found at: plugins[0]
(@/src/themes/docsy/postcss.config.js)`

I am pretty sure this was working in the past, and I made sure to run the npm commands mentioned in the documentation. Where should I look at to resolve this?

**Comment by tdufaure** [comment] 2020-09-16 19:03
Same problem here as I decided to update everything (hugo, docsy theme, npm packages).
For the following test I created a new hugo site and made a clean git clone of the theme repo.

`tstdocsy git:(master) ✗ hugo version`
`Hugo Static Site Generator v0.75.1-A4A7BAB7/extended linux/amd64 BuildDate: 2020-09-15T06:57:20Z`

`npm list autoprefixer`
`npm info using npm@6.14.6`
`npm info using node@v12.18.4`
`/workspaces/gitd4ta/tstdocsy`
`└── autoprefixer@10.0.0`
`npm list postcss-cli`
`/workspaces/gitd4ta/tstdocsy`
`└── postcss-cli@7.1.2`

`hugo --verbose`
`INFO 2020/09/16 17:41:03 postcss: use config file /workspaces/gitd4ta/tstdocsy/themes/docsy/postcss.config.js`
`INFO 2020/09/16 17:41:20 postcss: TypeError: Invalid PostCSS Plugin found at: plugins[0]`

In fact it seems to be related to this version 10 of `autoprefixer`.

With `npm install --save autoprefixer@9.8.6`, hugo runs just fine. Can you give it a try @brunoamaral ?

_au revoir,_

**Comment by brunoamaral** [comment] 2020-09-17 09:28
Thank you @tdufaure it looks like that was it. 

I am seeing a new error, but it's regarding postCSS so it's not related to this one, right?

**Comment by tdufaure** [comment] 2020-09-17 09:30
which error do you see now ?

**Comment by brunoamaral** [comment] 2020-09-17 09:39
```
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed: file "/src/themes/docsy/assets/scss/_boxes.scss", line 37, col 18: wrong number of arguments (3 for 2) for `bg-gradient-variant' 
```
I am trying to update dependencies to see if it fixes it.

**Comment by aimeeu** [comment] 2020-10-06 20:02
I'm getting the same error. @brunoamaral did you find a solution?
> ```
> Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed: file "/src/themes/docsy/assets/scss/_boxes.scss", line 37, col 18: wrong number of arguments (3 for 2) for `bg-gradient-variant' 
> ```

**Comment by brunoamaral** [comment] 2020-10-06 21:16
@aimeeu if I remember correctly it was solved when I upgraded dependencies.

**Comment by devboldium** [comment] 2020-10-27 18:12
Based on @brunoamaral 's reply, I updated postcss-cli and it fixed my issue

**Comment by chalin** [comment] 2022-08-18 08:32
This has been open for a while. I'm going to assume that the [final problem]() that you report is a duplicate of #464, which you can resolve by upgrading Node. For details see,  [Install/Upgrade Node.js](https://www.docsy.dev/docs/get-started/docsy-as-module/installation-prerequisites/#installupgrade-nodejs). I'll close this for now, if you still have the problem, please create a new issue.

**Closed by chalin** 2022-08-18 08:32 UTC
