### ISSUE TITLE
Add a "Time to read" option to the template

### ISSUE THREAD

**Issue by rionam** [google/docsy#172] opened 2020-01-13 16:56 UTC
"Time to read" is gaining traction: Azure uses it on its docs and Google Docs is also using it. 

One possible implementation: https://github.com/michael-lynch/reading-time

**Comment by LisaFC** [comment] 2020-01-14 16:56
Duplicate of #122

**Comment by LisaFC** [comment] 2023-05-26 09:25
Closed as fixed.

**Closed by LisaFC** 2023-05-26 09:25 UTC
