### ISSUE TITLE
"Edit this page" link on content pages includes language short name even in absense of a language folder 

### ISSUE THREAD

**Issue by ppipada** [google/docsy#308] opened 2020-07-17 08:09 UTC
I am using docsy without multilanguage support. 
My content directly lies in folders `content/docs`, `content/about`, etc.
I have commented out the whole language section in my config.toml. Also, `defaultContentLanguage` and `defaultContentLanguageInSubdir` is commented out. 

Even after this, the "Edit this page" metalink on content pages points to language specific url on github. 
E.g: On docs index page the link will incorrectly point to:  `https://<repo url>/edit/master/content/en/docs/_index.md`. 

The correct link for this should be: `https://<repo url>/edit/master/content/docs/_index.md`. Notice the absent "en".

**Comment by LisaFC** [comment] 2020-07-20 10:33
Duplicate of #138

**Comment by LisaFC** [comment] 2020-07-20 10:34
Still trying to figure out a nice solution for this but in the meantime see the workaround I suggested in #296, should fix it.

**Closed** 2020-07-21 00:33 UTC
