### ISSUE TITLE
Code sample followed by heading causes scrolling issue

### ISSUE THREAD

**Issue by kimberleybrown** [google/docsy#1194] opened 2022-08-19 18:26 UTC
Hello,

I've noticed a peculiar issue with the theme. If there is a code sample that has a horizontal bar appear on it and it is followed by a heading, the margin on that heading overlaps the element above and causes the horizontal scrolling bar to be dysfunctional. 

See the attached image in the issue. You'll notice that the margins created by the heading covers the horizontal bar of the above code sample, causing the horizontal bar to not be clickable and useable.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/25205867/185680195-ea65ecbc-4a50-47fe-b240-0fced8ea28e9.png)

Thank you!

**Comment by LisaFC** [comment] 2022-09-13 11:04
Huh, that's weird. Let me take a look.

**Comment by raum51** [comment] 2022-09-13 19:05
It's not only, when there is a scrolling bar before the headline. All h2 - h5 have an empty content before the headline text as offset for the anchor links:

```
@media (min-width: 768px)
h2[id]:before, h3[id]:before, h4[id]:before, h5[id]:before {
    display: block;
    content: " ";
    margin-top: -5rem;
    height: 5rem;
    visibility: hidden;
}
```

But this shouldn't effect the functionality of the scrolling bar.

**Comment by kimberleybrown** [comment] 2022-09-13 19:23
Thanks for the comments! I see in the above taxonomy_terms_could that the scrollbar is working properly above a heading.

Here is a link to a page in our documentation where we see the issue occurring on our end: [Doc](https://delightful-sky-04247a60f.1.azurestaticapps.net/mix/apis/asr-grpc/v1/samples/client-samples-training-h/#edit-input-files)

![image](https://user-images.githubusercontent.com/25205867/189991220-45b061f7-889b-4bd1-b329-6e9eddc8ced8.png)

The scrollbar in the code sample above the heading is not functional as described in the original post.

Thanks for taking the time again!

**Comment by kimberleybrown** [comment] 2022-09-13 19:44
I'm on Windows, just tried Chrome, Firefox, and Edge. Only Edge was able to move the scrollbar properly.

Updated Chrome to version 105.0.5195.127, now it works.

Firefox is on version 104.0.2 with no updates pending but it still doesn't work.

Unsure what a proper longterm solution to this is as I can't guarantee what browser versions users are running and it compromises a functional user experience.

**Comment by kimberleybrown** [comment] 2022-09-13 19:48
I should add, it's more the action of physically clicking and dragging the scrollbar if you were to be using a mouse, as opposed to sliding on a mousepad which seems to cause no issue.

**Comment by raum51** [comment] 2022-09-13 20:31
I was able to reproduce it on Firefox on Win and should have found a bugfix using z-index. I will test it tomorrow.

**Comment by kimberleybrown** [comment] 2022-09-13 20:49
Interesting that the issue could be something related to the z-index. Thank you!

**Comment by raum51** [comment] 2022-09-14 06:23
It's not really related to the z-index, but hopefully the bug can get fixed with z-index.

To scroll to the correct position when using anchor links the headlines get an vertical intercept by adding an empty content displayed as block before the original headline text by CSS. And it looks like this empty block is above the scoll bar on Windows-Firefox. So I try switch position by using z-index.

**Comment by kimberleybrown** [comment] 2022-09-27 21:37
Any updates on this?

**Comment by kimberleybrown** [comment] 2022-10-26 16:37
Want to bump this again as it is an ongoing issue with no suitable fix yet.

**Comment by LisaFC** [comment] 2022-10-27 11:16
@raum51 did you find anything tweaking the z-index?

**Comment by LisaFC** [comment] 2023-05-24 11:31
...and/or it's been fixed in the latest version of Firefox, which we have no control over...

I think once the bug is isolated to a previous version of Firefox we can consider it as obsolete and/or a Firefox bug because users can fix it by upgrading their browser, I don't think it's feasible to assume we can create sites that will work on all browsers including old versions.

**Comment by LisaFC** [comment] 2023-05-24 16:22
Hurrah! Thanks for letting me know.

**Closed by LisaFC** 2023-05-24 16:22 UTC
