### ISSUE TITLE
sidebar_menu_truncate needs to be documented

### ISSUE THREAD

**Issue by gary-vertica** [google/docsy#979] opened 2022-04-18 16:14 UTC
I just spent a day tearing my hair out trying to determine why some pages were being excluded from the section menu of our documentation. While looking into another issue I'm having with Docsy, I stumbled across a mention of the sidebar_menu_truncate param in [PR #475](https://github.com/google/docsy/pull/475). Sure enough, when I set this parameter to higher than the default value of 50, the missing pages appeared in the section menu. 

I can't find any reference to this parameter in the [distributed config.toml file](https://github.com/google/docsy-example/blob/master/config.toml), nor is it mentioned in the documentation. I can't understand why this parameter exists in the first place. It isn't intuitive to arbitrarily start excluding pages of documentation from the primary navigation menu when there are more than  50 pages in a section. But at the very least it needs to be either in the default config.toml or mentioned in the documentation. Preferably both.

**Comment by raum51** [comment] 2022-04-18 20:17
Hi, I'm the contributor of PR #475 (but with a new user name). As the PR is quiet long ago, I can't remember the details, but before my PR it was hardcoded in the `sidebar-tree.html`, that only only for the first 50 pages links got generated.

In my PR I've made some restructure of the sidebar generation and changed the before hardcoded limit of 50 pages to the undocumented option `sidebar_menu_truncate`, as this limit also wasn't documented before my PR.

@LisaFC I would say, https://www.docsy.dev/docs/adding-content/navigation/#section-menu-options would be the right place to describe this parameter. What's your opinion?

**Comment by fekete-robert** [comment] 2023-02-22 14:12
Seems there is an open PR for that: https://github.com/google/docsy/pull/1334
Also, do you think that we could increase this default to ~1-200? I've just ran into this issue again, and took some time to remember and find the root cause :)

**Comment by fekete-robert** [comment] 2023-02-23 15:42
See also https://github.com/google/docsy/pull/1438 to show a warning during build if the toc is truncated

**Comment by keawest** [comment] 2024-01-16 08:11
Happy i found this issue since i ran into this problem myself recently, "sidebar_menu_truncate" should get a mention in the documentation.

**Comment by chalin** [comment] 2024-08-07 16:21
- Closed via #1334
- Will also merge the following once I get a review and approval: #2069

**Closed by chalin** 2024-08-07 16:21 UTC

**Comment by chalin** [comment] 2024-08-07 16:44
> Also, do you think that we could increase this default to ~1-200? I've just ran into this issue again, and took some time to remember and find the root cause :)

Yes, let's bump it up by 100%.
