### ISSUE TITLE
Inconsistent behavior when including code snippets in an alert 

### ISSUE THREAD

**Issue by sharifsalah** [google/docsy#183] opened 2020-01-29 13:51 UTC
Currently, when we include a code snippet in an alert we see inconsistent behavior:

1.  Using back ticks:

```
{{% alert %}} Here's an example command:

    ```shell
    my example command
    ```

    {{% /alert %}}
```

Results in the back ticks displaying in the rendered HTML.

2.  Using indentation alone:

```
{{% alert %}} Here's an example command:

    my example command

    {{% /alert %}}
```

Results in the code snippet rendering correctly (even though the command isn't really indented).

For screenshots, see https://github.com/AcademySoftwareFoundation/opencue.io/pull/147

**Comment by LisaFC** [comment] 2020-01-29 14:45
I'll have a look! Which version of Hugo are you using? The 0.60 versions and up use a different Markdown processor (Goldmark) which is mildly less weird than Blackfriday.

**Comment by sharifsalah** [comment] 2020-01-29 15:20
Thanks @LisaFC! We're running a version of Hugo prior to 0.6.0, so I'll experiment with updating and report back if that fixes the behavior.

**Comment by LisaFC** [comment] 2020-01-29 15:29
Be aware that it may break other things! :)

https://www.docsy.dev/docs/adding-content/content/#page-contents-and-markup

There's also a rogue div that may appear on your landing page depending on how much customization you did, which you can just delete: #174

**Comment by sharifsalah** [comment] 2020-01-29 15:39
Thanks again, that all helped!

To update you on the original issue, I've tried updating Hugo, Docsy, and enabling HTML in Markdown. The site is generally looking as expected. I can still see the strange behavior in the description for this issue:

https://deploy-preview-150--elated-haibt-1b47ff.netlify.com/docs/getting-started/setting-up-the-database/

If you want to see it, you can search for the following string on that page:

```shell

Not a big issue but worth reporting :)

**Comment by LisaFC** [comment] 2020-01-29 15:50
Ok! Let's see if I can figure it out....

**Comment by RichieEscarez** [comment] 2020-02-20 00:14
This sounds like it might be the cause: https://github.com/gohugoio/hugo/issues/5831#issuecomment-484061721

**Comment by LisaFC** [comment] 2023-05-26 09:31
Closing as looks like this was fixed in Hugo.

**Closed by LisaFC** 2023-05-26 09:31 UTC
