### ISSUE TITLE
Rendering with offlineSearch fails: offline-search-index.json:750: comment ends before closing delimiter

### ISSUE THREAD

**Issue by marians** [google/docsy#705] opened 2021-09-29 15:32 UTC
With hugo 0.88.1 and the latest Docsy from master I get the following error when rendering a site with `offlineSearch = true`:

```
Error: Error building site: EXECUTE-AS-TEMPLATE: failed to transform "offline-search-index.json" (application/json): failed to parse Resource "offline-search-index.json" as Template:: template: offline-search-index.json:750: comment ends before closing delimiter
```

The file mentioned is https://github.com/google/docsy/blob/ea64eddd6be4c754cb207e79ebd6a6ca05ea4f08/assets/json/offline-search-index.json

By trial and error I have narrowed down the problem to the rendering of the "body" attribute. When I remove the ` "body" (.Plain | htmlUnescape) ` part from the template, the error disappears and the file is generated just fine.

So I'm guessing the escaping of the body field isn't happening as it should be.

Unfortunately the content is not public. Anything I can do to narrow down the problem?

**Comment by LukeTimeWalker** [comment] 2021-09-30 11:11
We get a similar error when we try to build our hugo project using the latest docsy theme.
```
Error: Error building site: EXECUTE-AS-TEMPLATE: failed to transform "offline-search-index.json" (application/json): failed to parse Resource "offline-search-index.json" as Template:: template: offline-search-index.json:453: function "ansible_env" not defined
```
As far as I know, the problem is because our offline-search-index.json contains two curly braces. Through the resources.ExecuteAsTemplate pipe, hugo tries to render the JSON file with templates (which are also indicated by two curly braces in hugo).

https://github.com/google/docsy/blob/170cdd9cd31794eac802b0cec083097155feb81b/layouts/partials/search-input.html#L4

In my opinion there is no reason to 'render' the search index with templates.

Without the ExecuteAsTemplate Pipe the project can be build without any errors.

**Comment by LisaFC** [comment] 2021-09-30 15:43
@tekezo do you want to take a look? I can take a look as well tomorrow.

**Comment by tekezo** [comment] 2021-10-04 00:27
I have confirmed the issue in my environment.
(This issue only happens when `{{` is included in contents.)

It seems the problem is caused by Hugo side, Hugo evaluates the contents of variable as template at accessing variable by Scratch.Get, it should be fixed in Hugo.

I'll continue to investigate the right way to how to fix this.

**Comment by tekezo** [comment] 2021-10-04 14:40
I fixed docsy template to avoid this issue at https://github.com/google/docsy/pull/710 .

@LisaFC Could you review and merge the PR?

**Comment by LisaFC** [comment] 2021-10-04 14:43
Fixed in #710

**Closed by LisaFC** 2021-10-04 14:43 UTC

**Comment by marians** [comment] 2021-10-05 07:50
After updating to version https://github.com/google/docsy/commit/e4bb26bafcc48fb72296e0cc584a2ff5bbf0610c im am now getting a slightly different error:

```
ERROR 2021/10/05 07:44:22 EXECUTE-AS-TEMPLATE: failed to transform "json/offline-search-index.json" (application/json): failed to parse Resource "json/offline-search-index.json" as Template:: template: json/offline-search-index.json:5: unclosed action
```

**Comment by marians** [comment] 2021-10-05 08:26
Please ignore the above comment. I can't reproduce that error any more in a fresh docker container.
