### ISSUE TITLE
Menu items dropped at some window sizes

### ISSUE THREAD

**Issue by tdcox** [google/docsy#1319] opened 2022-11-24 15:56 UTC
Using Docsy 0.5.1 as Hugo module.

We have a top level menu, containing three items, Documentation, Community and Releases.

When the browser window is less than 960 pixels wide, the dynamically generated Releases submenu item stops being rendered. The font size is also reduced for the remaining two items and their position is offset slightly.

![Screenshot 2022-11-24 at 15 40 57](https://user-images.githubusercontent.com/15021932/203823841-01e4e0c3-712e-45e3-aa5a-bce21ccaeb6f.png)

![Screenshot 2022-11-24 at 15 41 25](https://user-images.githubusercontent.com/15021932/203823935-c4062359-97af-4b35-9a7c-1fb064a7681d.png)

Observed behaviour is consistent in Chrome, Firefox and Safari.

It is unclear whether this is intentional, or a bug?

**Comment by LisaFC** [comment] 2023-05-24 11:23
Sorry for the very late reply - I've been taking a look at this now.  Is the vanishing drop down appearing in the left nav under the search bar, by any chance (as that's where it's showing up for me on a site with a version drop-down)? The formatting is a bit strange, mind, as it's waaaay off to the left.

![image](https://github.com/google/docsy/assets/10744406/99c91eea-c6a3-409d-886f-def0743dca58)

The text dropping down at "medium" width thing is no longer happening in the Docsy site (which is using the theme from head), which would indicate that it will be fixed/changed in the next release. @chalin any other thoughts?

**Comment by chalin** [comment] 2023-05-24 13:12
Releases disappearing under narrower displays is (or was if that behavior is no longer there) by design AFAIR. We could question the design of course, but that's the way it was coded. Practically speaking, it should be relatively easy to override locally to your project's preferences.

**Comment by tdcox** [comment] 2023-05-24 13:39
Thanks. The page in question doesn't have a left menu, so I can't tell if the dropdown migrates.

Feel free to close this if it is the intended behaviour.

**Comment by chalin** [comment] 2023-08-10 17:44
> Feel free to close this if it is the intended behaviour.

Closing.

**Closed by chalin** 2023-08-10 17:44 UTC
