### ISSUE TITLE
Feature request: Add tracking to the right nav

### ISSUE THREAD

**Issue by ArtFlag** [google/docsy#358] opened 2020-10-14 07:36 UTC
First of all, thanks for the theme, it's very useful. 

I'd like to suggest a new feature: tracking where the user is on the page, inside the right nav, [a la Docusaurus](https://docusaurus.io/docs/en/installation).

It's particularily useful in larger pages.

**Comment by LisaFC** [comment] 2020-10-14 11:26
Duplicate of 349

**Comment by LisaFC** [comment] 2020-10-14 11:27
Duplicate of #349

**Comment by quickstar** [comment] 2020-11-01 14:06
This issue should probable be closed since it's an obvious doublicate

**Closed** 2020-11-02 10:01 UTC
