### ISSUE TITLE
Create a new child page doesnt work.

### ISSUE THREAD

**Issue by robkle153** [google/docsy#1637] opened 2023-08-01 14:17 UTC
I would like to use the links on the right side menu at Docs/Blog to create a new child page. 
I followed the steps in the userguide but when redirecting to the git repo I get something like in the picture. 

![image](https://github.com/google/docsy/assets/139347669/ad75f7b3-f82a-4d70-8e32-d38486b0378b)

It overwrites the _index.md file and creates a folder from it.

![image](https://github.com/google/docsy/assets/139347669/81af716b-969d-4225-870b-130eb55102be)
![image](https://github.com/google/docsy/assets/139347669/c86d16bf-0e9a-4ef4-b60f-8cfd95b7e99c)

_Originally posted by @robkle153 in https://github.com/google/docsy/discussions/1636#discussioncomment-6605376_

**Comment by chalin** [comment] 2023-08-04 12:42
Duplicate of:

- #668

Will close this in favor of the original.

**Closed by chalin** 2023-08-04 12:42 UTC
