### ISSUE TITLE
page meta links should respect `.Site.IsMultiLingual`

### ISSUE THREAD

**Issue by tmc** [google/docsy#981] opened 2022-04-20 18:50 UTC
Currently, the page meta links will always include "en" even if the site is not multi-lingual and has content directly in the "contents" directory (vs "contents/en").

**Comment by LisaFC** [comment] 2022-04-21 17:41
This is a problem that has come up before (see #138) and we haven't found anything elegant that worked with the templating.  Hopefully now that we have a bigger community (and possibly Hugo has changed a bit) we can come up with a solution.

Duplicate of #138

**Closed as completed** 2024-02-01 14:26 UTC
Labels: i18n
